#on: push
#name: Jenkins single-shot master
#jobs:
#  jenkinsfile-runner-prepackaged:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@master
#      - name: Jenkinsfile Runner Prepackaged
#        uses: jenkinsci/jenkinsfile-runner-github-actions@v0.2
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

on: push
name: Jenkins single-shot master
jobs:
  jenkinsfile-runner-prepackaged:
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3

      - name: Set up Node.js 20.16.0
        uses: actions/setup-node@v4
        with:
          node-version: '20.16.0'

      - name: Install Yarn
        run: npm install -g yarn

      - name: Jenkinsfile Runner Prepackaged
        uses: jenkinsci/jenkinsfile-runner-github-actions@v0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
